In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Lasso
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV

In [3]:
df = pd.read_csv("rental_info.csv")

In [4]:
df.head()

                 rental_date  ... rental_rate_2
0  2005-05-25 02:54:33+00:00  ...        8.9401
1  2005-06-15 23:19:16+00:00  ...        8.9401
2  2005-07-10 04:27:45+00:00  ...        8.9401
3  2005-07-31 12:06:41+00:00  ...        8.9401
4  2005-08-19 12:30:04+00:00  ...        8.9401

[5 rows x 15 columns]

In [5]:
df["return_date"] = pd.to_datetime(df["return_date"])
df["rental_date"] = pd.to_datetime(df["rental_date"])
df.head()

                rental_date               return_date  ...  length_2  rental_rate_2
0 2005-05-25 02:54:33+00:00 2005-05-28 23:40:33+00:00  ...   15876.0         8.9401
1 2005-06-15 23:19:16+00:00 2005-06-18 19:24:16+00:00  ...   15876.0         8.9401
2 2005-07-10 04:27:45+00:00 2005-07-17 10:11:45+00:00  ...   15876.0         8.9401
3 2005-07-31 12:06:41+00:00 2005-08-02 14:30:41+00:00  ...   15876.0         8.9401
4 2005-08-19 12:30:04+00:00 2005-08-23 13:35:04+00:00  ...   15876.0         8.9401

[5 rows x 15 columns]

In [6]:
df["rental_length"] = pd.to_datetime(df["return_date"]) - pd.to_datetime(df["rental_date"])
df["rental_length_days"] = df["rental_length"].dt.days
df.head()

                rental_date  ... rental_length_days
0 2005-05-25 02:54:33+00:00  ...                  3
1 2005-06-15 23:19:16+00:00  ...                  2
2 2005-07-10 04:27:45+00:00  ...                  7
3 2005-07-31 12:06:41+00:00  ...                  2
4 2005-08-19 12:30:04+00:00  ...                  4

[5 rows x 17 columns]

In [7]:
df["deleted_scenes"] =  np.where(df["special_features"].str.contains("Deleted Scenes"), 1,0)
df["behind_the_scenes"] =  np.where(df["special_features"].str.contains("Behind the Scenes"), 1, 0)
df.head()

                rental_date  ... behind_the_scenes
0 2005-05-25 02:54:33+00:00  ...                 1
1 2005-06-15 23:19:16+00:00  ...                 1
2 2005-07-10 04:27:45+00:00  ...                 1
3 2005-07-31 12:06:41+00:00  ...                 1
4 2005-08-19 12:30:04+00:00  ...                 1

[5 rows x 19 columns]

In [8]:
df["special_features"].unique()

array(['{Trailers,"Behind the Scenes"}', '{Trailers}',
       '{Commentaries,"Behind the Scenes"}', '{Trailers,Commentaries}',
       '{"Deleted Scenes","Behind the Scenes"}',
       '{Commentaries,"Deleted Scenes","Behind the Scenes"}',
       '{Trailers,Commentaries,"Deleted Scenes"}',
       '{"Behind the Scenes"}',
       '{Trailers,"Deleted Scenes","Behind the Scenes"}',
       '{Commentaries,"Deleted Scenes"}', '{Commentaries}',
       '{Trailers,Commentaries,"Behind the Scenes"}',
       '{Trailers,"Deleted Scenes"}', '{"Deleted Scenes"}',
       '{Trailers,Commentaries,"Deleted Scenes","Behind the Scenes"}'],
      dtype=object)

In [9]:
cols_to_drop = [
    "return_date",
    "rental_date",
    "rental_length",
    "special_features"
]

df = df.drop(columns=cols_to_drop)
df.head()

   amount  release_year  ...  deleted_scenes  behind_the_scenes
0    2.99        2005.0  ...               0                  1
1    2.99        2005.0  ...               0                  1
2    2.99        2005.0  ...               0                  1
3    2.99        2005.0  ...               0                  1
4    2.99        2005.0  ...               0                  1

[5 rows x 15 columns]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15861 entries, 0 to 15860
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amount              15861 non-null  float64
 1   release_year        15861 non-null  float64
 2   rental_rate         15861 non-null  float64
 3   length              15861 non-null  float64
 4   replacement_cost    15861 non-null  float64
 5   NC-17               15861 non-null  int64
 6   PG                  15861 non-null  int64
 7   PG-13               15861 non-null  int64
 8   R                   15861 non-null  int64
 9   amount_2            15861 non-null  float64
 10  length_2            15861 non-null  float64
 11  rental_rate_2       15861 non-null  float64
 12  rental_length_days  15861 non-null  int64
 13  deleted_scenes      15861 non-null  int64
 14  behind_the_scenes   15861 non-null  int64
dtypes: float64(8), int64(7)
memory usage: 1.8 MB

In [11]:
df.apply(lambda col: col.unique())

amount                [2.99, 4.99, 3.99, 0.99, 1.99, 6.99, 5.99, 8.9...
release_year          [2005.0, 2009.0, 2006.0, 2004.0, 2008.0, 2007....
rental_rate                                          [2.99, 0.99, 4.99]
length                [126.0, 156.0, 181.0, 84.0, 92.0, 123.0, 56.0,...
replacement_cost      [16.99, 14.99, 21.99, 29.99, 19.99, 12.99, 9.9...
NC-17                                                            [0, 1]
PG                                                               [0, 1]
PG-13                                                            [0, 1]
R                                                                [1, 0]
amount_2              [8.940100000000001, 24.9001, 15.9201, 0.9801, ...
length_2              [15876.0, 24336.0, 32761.0, 7056.0, 8464.0, 15...
rental_rate_2                      [8.940100000000001, 0.9801, 24.9001]
rental_length_days                       [3, 2, 7, 4, 5, 1, 6, 8, 9, 0]
deleted_scenes                                                   [0, 1]
behind_the_scenes                                                [1, 0]
dtype: object

In [12]:
df.isna().sum()

amount                0
release_year          0
rental_rate           0
length                0
replacement_cost      0
NC-17                 0
PG                    0
PG-13                 0
R                     0
amount_2              0
length_2              0
rental_rate_2         0
rental_length_days    0
deleted_scenes        0
behind_the_scenes     0
dtype: int64

In [13]:
X = df.drop(columns=["rental_length_days"])
y = df["rental_length_days"]

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=9)

In [15]:
scaler = StandardScaler()
num_cols = [
    "amount",
    "rental_rate",
    "replacement_cost",
    "length",
    "release_year",
    "amount_2",
    "rental_rate_2",
    "length_2"
]

X_train[num_cols] = scaler.fit_transform(X_train[num_cols])

X_test[num_cols] = scaler.transform(X_test[num_cols])

In [16]:
lasso = Lasso(alpha=0.3, random_state=9)
lasso.fit(X_train, y_train)

lasso_coef = lasso.coef_

X_lasso_train, X_lasso_test = X_train.iloc[:, lasso_coef > 0], X_test.iloc[:, lasso_coef > 0]

In [17]:
lr = LinearRegression()
lr.fit(X_lasso_train, y_train)
lr_pred = lr.predict(X_lasso_test)
lr_mse = mean_squared_error(y_test, lr_pred)
lr_mse

4.845903109515722

In [18]:
param_dist = {'n_estimators': np.arange(1,101,1),
          'max_depth':np.arange(1,11,1)}

rf = RandomForestRegressor(random_state=42, n_jobs=-1)

rand_search = RandomizedSearchCV(rf, 
                                 param_distributions=param_dist, 
                                 cv=5, 
                                 random_state=9)
rand_search.fit(X_train, y_train)
hyper_params = rand_search.best_params_
hyper_params

{'n_estimators': 51, 'max_depth': 10}

In [19]:
rf = RandomForestRegressor(n_estimators=hyper_params["n_estimators"], 
                           max_depth=hyper_params["max_depth"], 
                           random_state=9)
rf.fit(X_train,y_train)
rf_pred = rf.predict(X_test)
mse_random_forest= mean_squared_error(y_test, rf_pred)
mse_random_forest

2.2252146023776667

In [21]:
best_model = rf
best_mse = mse_random_forest

In [23]:
print(best_model)
print(best_mse)

RandomForestRegressor(max_depth=10, n_estimators=51, random_state=9)
2.2252146023776667